# Generated by Django 5.2.4 on 2025-07-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_participantresult_quizattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
