# Generated by Django 5.2.4 on 2025-07-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_option_option'),
        ('participant', '0003_alter_participant_ip_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('participant', 'quiz', 'option')},
        ),
    ]
