# Generated by Django 5.2.4 on 2025-07-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_alter_quizattempt_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantresult',
            name='count',
        ),
        migrations.AlterField(
            model_name='participantresult',
            name='option',
            field=models.CharField(max_length=1),
        ),
    ]
