# Generated by Django 5.2.4 on 2025-07-14 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_option_question'),
        ('participant', '0005_remove_participantresult_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantresult',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='participant.participant'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.option'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='participant.participant'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.quiz'),
        ),
    ]
