# Generated by Django 5.2.4 on 2025-07-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0006_alter_participantresult_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantresult',
            name='card_name',
            field=models.CharField(choices=[('', ''), ('The Explorer', 'The Explorer'), ('The Socializer', 'The Socializer'), ('The Storyteller', 'The Storyteller')], default='', max_length=20, null=True),
        ),
    ]
