# Generated by Django 5.2.4 on 2025-07-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0007_alter_participantresult_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='class_type',
            field=models.CharField(choices=[('', ''), ('Premium', 'Premium'), ('Economy', 'Economy')], default='', max_length=20, null=True),
        ),
    ]
