# Generated by Django 6.0.3 on 2026-04-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0008_participant_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='location',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
