# Generated by Django 6.0.3 on 2026-04-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0009_participant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantresult',
            name='card_name',
            field=models.CharField(choices=[('', ''), ('The Main Character', 'The Main Character'), ('The Social Anchor', 'The Social Anchor'), ('Ever Curious', 'Ever Curious')], default='', max_length=20, null=True),
        ),
    ]
