# Generated by Django 5.2.4 on 2025-07-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.CharField(max_length=500),
        ),
    ]
