# Generated by Django 5.2.4 on 2025-07-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_option_option_alter_option_option_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.TextField(max_length=500),
        ),
    ]
