# Generated by Django 5.2.4 on 2025-07-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_option_option_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default='1', max_length=1, null=True),
        ),
    ]
