# Generated by Django 5.2.4 on 2025-07-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_option_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.TextField(max_length=500),
        ),
    ]
